# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    command: /bin/bash /srv/jekyll/bin/custom_entry_point.sh
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
